# set up cache to speed up builds
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cargo/
    - .cache/sccache

# setup sccache
before_script:
  - export CARGO_HOME="${PWD}/.cargo"
  - export SCCACHE_DIR="${PWD}/.cache/sccache"

stages:
  - test
  - build
  - deploy

rustfmt:
  image: registry.gitlab.com/fractalnetworks/images/rust-stable:v1
  stage: test
  allow_failure: true
  script:
    - cargo fmt -- --check

clippy:
  image: registry.gitlab.com/fractalnetworks/images/rust-stable:v1
  stage: test
  allow_failure: true
  script:
    - cargo clippy

test:
  image: registry.gitlab.com/fractalnetworks/images/rust-stable:v1
  stage: test
  script:
    - cargo test --all-features

# generate rust html documentation
rustdoc:
  image: registry.gitlab.com/fractalnetworks/images/rust-stable:v1
  stage: build
  script:
    - cargo doc --all-features --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week

# publish binary, docs and API docs to gitlab pages.
pages:
  image: registry.gitlab.com/fractalnetworks/images/pages
  stage: deploy
  dependencies:
    - rustdoc
  script:
    - mkdir public
    - mv target/doc public/doc
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
